export const ROOMS_UPDATED = "ROOMS_UPDATED"

export const USER_JOINED = "USER_JOINED"
export const USER_MOVED_TO_ROOM = "USER_MOVED_TO_ROOM"
export const USER_LEFT = "USER_LEFT"

export const CHAT_HISTORY = "CHAT_HISTORY"
export const ADD_MESSAGE = "ADD_MESSAGE"